//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GearConfig
    {
        public int ID { get; set; }
        public int Code { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string FieldGearID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public bool Valid { get; set; }
    }
}
