//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundICPOrigional
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public Nullable<int> tblSampleID { get; set; }
        public string DUPLICATE { get; set; }
        public Nullable<decimal> AL_D { get; set; }
        public Nullable<decimal> AL_T { get; set; }
        public Nullable<decimal> AS_D { get; set; }
        public Nullable<decimal> AS_T { get; set; }
        public Nullable<decimal> CA_D { get; set; }
        public Nullable<decimal> CA_T { get; set; }
        public Nullable<decimal> CD_D { get; set; }
        public Nullable<decimal> CD_T { get; set; }
        public Nullable<decimal> CU_D { get; set; }
        public Nullable<decimal> CU_T { get; set; }
        public Nullable<decimal> FE_D { get; set; }
        public Nullable<decimal> FE_T { get; set; }
        public Nullable<decimal> PB_D { get; set; }
        public Nullable<decimal> PB_T { get; set; }
        public Nullable<decimal> MG_D { get; set; }
        public Nullable<decimal> MG_T { get; set; }
        public Nullable<decimal> MN_D { get; set; }
        public Nullable<decimal> MN_T { get; set; }
        public Nullable<decimal> SE_D { get; set; }
        public Nullable<decimal> SE_T { get; set; }
        public Nullable<decimal> ZN_D { get; set; }
        public Nullable<decimal> ZN_T { get; set; }
        public Nullable<decimal> NA_D { get; set; }
        public Nullable<decimal> NA_T { get; set; }
        public Nullable<decimal> K_D { get; set; }
        public Nullable<decimal> K_T { get; set; }
        public Nullable<System.DateTime> ANADATE { get; set; }
        public Nullable<bool> COMPLETE { get; set; }
        public Nullable<System.DateTime> DATE_SENT { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Valid { get; set; }
        public bool Edited { get; set; }
        public bool Saved { get; set; }
    }
}
