//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundSample
    {
        public int ID { get; set; }
        public Nullable<int> StationNum { get; set; }
        public string SampleID { get; set; }
        public string txtSampleID { get; set; }
        public Nullable<int> KitNum { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<decimal> USGSFlow { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<decimal> TempC { get; set; }
        public Nullable<decimal> PhenAlk { get; set; }
        public Nullable<decimal> TotalAlk { get; set; }
        public Nullable<decimal> TotalHard { get; set; }
        public Nullable<decimal> DO { get; set; }
        public Nullable<decimal> DOsat { get; set; }
        public string Tag { get; set; }
        public string Chk { get; set; }
        public Nullable<int> EntryType { get; set; }
        public string EntryStaff { get; set; }
        public Nullable<bool> MetalsNormal { get; set; }
        public Nullable<bool> MetalsBlnk { get; set; }
        public Nullable<bool> MetalsDupe { get; set; }
        public Nullable<bool> Bugs { get; set; }
        public Nullable<bool> BugsQA { get; set; }
        public Nullable<bool> TSS { get; set; }
        public Nullable<bool> CS { get; set; }
        public Nullable<bool> NP { get; set; }
        public Nullable<bool> TSSDupe { get; set; }
        public Nullable<bool> CSDupe { get; set; }
        public Nullable<bool> NPDupe { get; set; }
        public Nullable<bool> FieldValid { get; set; }
        public Nullable<int> MetalsStat { get; set; }
        public Nullable<bool> FinalCheck { get; set; }
        public Nullable<int> Method { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<bool> DataSheetIncluded { get; set; }
        public Nullable<System.DateTime> MissingDataSheetReqDate { get; set; }
        public Nullable<bool> ChainOfCustody { get; set; }
        public Nullable<bool> MissingDataSheetReceived { get; set; }
        public Nullable<decimal> PassValStep { get; set; }
        public Nullable<int> tblSampleID { get; set; }
        public Nullable<bool> Valid { get; set; }
    }
}
