//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lachat
    {
        public int inbLachatID { get; set; }
        public string Batch { get; set; }
        public string SampleType { get; set; }
        public string SampleDescription { get; set; }
        public string CODE { get; set; }
        public string Parameter { get; set; }
        public Nullable<decimal> Result { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> AnalDate { get; set; }
        public Nullable<bool> CONHI { get; set; }
        public Nullable<decimal> RPDDivPctREC { get; set; }
        public Nullable<bool> CHANGED { get; set; }
        public Nullable<int> NumChanged { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> PassValStep { get; set; }
        public Nullable<int> tblSampleID { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<bool> Validated { get; set; }
        public Nullable<bool> BlkDup { get; set; }
        public Nullable<bool> Failed { get; set; }
    }
}
