//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWexpWater
    {
        public int ID { get; set; }
        public Nullable<int> tblSampleID { get; set; }
        public string SampleNumber { get; set; }
        public string Event { get; set; }
        public string WaterShed { get; set; }
        public Nullable<double> River_CD { get; set; }
        public string RiverName { get; set; }
        public Nullable<int> KitNumber { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<short> StationNumber { get; set; }
        public string TypeCode { get; set; }
        public string StationName { get; set; }
        public string MetalsBarCode { get; set; }
        public string NutrientBarCode { get; set; }
        public string FieldBarCode { get; set; }
        public string BugsBarCode { get; set; }
        public System.DateTime SampleDate { get; set; }
        public Nullable<double> USGS_Flow { get; set; }
        public Nullable<double> PH { get; set; }
        public Nullable<double> TempC { get; set; }
        public Nullable<double> PHEN_ALK { get; set; }
        public Nullable<double> TOTAL_ALK { get; set; }
        public Nullable<double> TOTAL_HARD { get; set; }
        public Nullable<double> DO_MGL { get; set; }
        public Nullable<short> DOSAT { get; set; }
        public Nullable<decimal> AL_D { get; set; }
        public Nullable<decimal> AL_T { get; set; }
        public Nullable<decimal> AS_D { get; set; }
        public Nullable<decimal> AS_T { get; set; }
        public Nullable<decimal> CA_D { get; set; }
        public Nullable<decimal> CA_T { get; set; }
        public Nullable<decimal> CD_D { get; set; }
        public Nullable<decimal> CD_T { get; set; }
        public Nullable<decimal> CU_D { get; set; }
        public Nullable<decimal> CU_T { get; set; }
        public Nullable<decimal> FE_D { get; set; }
        public Nullable<decimal> FE_T { get; set; }
        public Nullable<decimal> MG_D { get; set; }
        public Nullable<decimal> MG_T { get; set; }
        public Nullable<decimal> MN_D { get; set; }
        public Nullable<decimal> MN_T { get; set; }
        public Nullable<decimal> PB_D { get; set; }
        public Nullable<decimal> PB_T { get; set; }
        public Nullable<decimal> SE_D { get; set; }
        public Nullable<decimal> SE_T { get; set; }
        public Nullable<decimal> ZN_D { get; set; }
        public Nullable<decimal> ZN_T { get; set; }
        public Nullable<decimal> NA_D { get; set; }
        public Nullable<decimal> NA_T { get; set; }
        public Nullable<decimal> K_D { get; set; }
        public Nullable<decimal> K_T { get; set; }
        public Nullable<int> Rep { get; set; }
        public Nullable<double> Ammonia { get; set; }
        public Nullable<double> Chloride { get; set; }
        public Nullable<double> ChlorophyllA { get; set; }
        public Nullable<double> DOC { get; set; }
        public Nullable<double> NN { get; set; }
        public Nullable<double> OP { get; set; }
        public Nullable<double> Sulfate { get; set; }
        public Nullable<double> totN { get; set; }
        public Nullable<double> totP { get; set; }
        public Nullable<double> TKN { get; set; }
        public Nullable<double> orgN { get; set; }
        public Nullable<double> TSS { get; set; }
        public Nullable<int> Batch { get; set; }
        public string SampleComments { get; set; }
        public string FieldComment { get; set; }
        public string NutrientComment { get; set; }
        public string MetalsComment { get; set; }
        public string BugsComments { get; set; }
        public string BenthicsComments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> BadBlank { get; set; }
        public Nullable<bool> BadDuplicate { get; set; }
        public Nullable<bool> BadSample { get; set; }
        public bool Valid { get; set; }
    }
}
