//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutrientBarCode
    {
        public int ID { get; set; }
        public Nullable<int> SampleID { get; set; }
        public string SampleNumber { get; set; }
        public string LabID { get; set; }
        public string Batch { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> AnalyzeDate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public Nullable<bool> TotalPhos { get; set; }
        public Nullable<bool> OrthoPhos { get; set; }
        public Nullable<bool> TotalNitro { get; set; }
        public Nullable<bool> NitrateNitrite { get; set; }
        public Nullable<bool> Ammonia { get; set; }
        public Nullable<bool> DOC { get; set; }
        public Nullable<bool> Chloride { get; set; }
        public Nullable<bool> Sulfate { get; set; }
        public Nullable<bool> TSS { get; set; }
        public Nullable<bool> ChlorA { get; set; }
    }
}
