//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutrientData
    {
        public int ID { get; set; }
        public string BARCODE { get; set; }
        public string Batch { get; set; }
        public string TypeCode { get; set; }
        public string SampleNumber { get; set; }
        public Nullable<decimal> TotalPhos { get; set; }
        public Nullable<bool> TotalPhos_CH { get; set; }
        public Nullable<decimal> OrthoPhos { get; set; }
        public Nullable<bool> OrthoPhos_CH { get; set; }
        public Nullable<decimal> TotalNitro { get; set; }
        public Nullable<bool> TotalNitro_CH { get; set; }
        public Nullable<decimal> NitrateNitrite { get; set; }
        public Nullable<bool> NitrateNitrite_CH { get; set; }
        public Nullable<decimal> Ammonia { get; set; }
        public Nullable<bool> Ammonia_CH { get; set; }
        public Nullable<decimal> DOC { get; set; }
        public Nullable<bool> DOC_CH { get; set; }
        public Nullable<decimal> Chloride { get; set; }
        public Nullable<bool> Chloride_CH { get; set; }
        public Nullable<decimal> Sulfate { get; set; }
        public Nullable<bool> Sulfate_CH { get; set; }
        public Nullable<decimal> TSS { get; set; }
        public Nullable<bool> TSS_CH { get; set; }
        public Nullable<decimal> ChlorA { get; set; }
        public Nullable<bool> ChlorA_CH { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<bool> Validated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
