//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutrientLimit
    {
        public int ID { get; set; }
        public string Element { get; set; }
        public string RowID { get; set; }
        public Nullable<decimal> Reporting { get; set; }
        public Nullable<decimal> MDL { get; set; }
        public Nullable<decimal> DvsTDifference { get; set; }
        public Nullable<decimal> HighLimit { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<bool> Valid { get; set; }
    }
}
