//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgStatu
    {
        public int ID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<bool> ContractSigned { get; set; }
        public Nullable<System.DateTime> ContractSignedDate { get; set; }
        public Nullable<bool> SiteVisited { get; set; }
        public Nullable<bool> VolunteerTimeSheet1 { get; set; }
        public Nullable<bool> VolunteerTimeShee2 { get; set; }
        public Nullable<bool> VolunteerTimeSheet3 { get; set; }
        public Nullable<bool> VolunteerTimeSheet4 { get; set; }
        public Nullable<bool> DataEnteredElectronically1 { get; set; }
        public Nullable<bool> DataEnteredElectronically2 { get; set; }
        public Nullable<bool> DataEnteredElectronically3 { get; set; }
        public Nullable<bool> DataEnteredElectronically4 { get; set; }
        public Nullable<bool> SampleShipped1 { get; set; }
        public Nullable<bool> SampleShipped2 { get; set; }
        public Nullable<bool> SampleShipped3 { get; set; }
        public Nullable<bool> SampleShipped4 { get; set; }
        public Nullable<int> NumberOfSamplesJan { get; set; }
        public Nullable<int> NumberOfSamplesFeb { get; set; }
        public Nullable<int> NumberOfSamplesMar { get; set; }
        public Nullable<int> NumberOfSamplesApr { get; set; }
        public Nullable<int> NumberOfSamplesMay { get; set; }
        public Nullable<int> NumberOfSamplesJun { get; set; }
        public Nullable<int> NumberOfSamplesJul { get; set; }
        public Nullable<int> NumberOfSamplesAug { get; set; }
        public Nullable<int> NumberOfSamplesSep { get; set; }
        public Nullable<int> NumberOfSamplesOct { get; set; }
        public Nullable<int> NumberOfSamplesNov { get; set; }
        public Nullable<int> NumberOfSamplesDec { get; set; }
        public Nullable<bool> Nutrient1Collected { get; set; }
        public Nullable<bool> Nutrient2Collected { get; set; }
        public Nullable<bool> BugCollected { get; set; }
        public Nullable<System.DateTime> UnknownSpringRecordedDate { get; set; }
        public Nullable<System.DateTime> UnknownFallRecordedDate { get; set; }
        public Nullable<int> NumberOfSamplesBlank { get; set; }
        public Nullable<int> NumberOfSamplesDuplicate { get; set; }
        public string TroubleComment { get; set; }
        public string NoteComment { get; set; }
        public string HardshipComment { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public Nullable<int> NumberOfMetalsBlank { get; set; }
        public Nullable<int> NumberOfMetalsDuplicate { get; set; }
    }
}
