//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public int ID { get; set; }
        public Nullable<int> StationNumber { get; set; }
        public string River { get; set; }
        public string AquaticModelIndex { get; set; }
        public string WaterCode { get; set; }
        public string WaterBodyID { get; set; }
        public string StationType { get; set; }
        public string QUADI { get; set; }
        public string Township { get; set; }
        public string Range { get; set; }
        public Nullable<int> Section { get; set; }
        public string QuaterSection { get; set; }
        public string Grid { get; set; }
        public string StationQUAD { get; set; }
        public string RWWaterShed { get; set; }
        public string WQCCWaterShed { get; set; }
        public string HydroUnit { get; set; }
        public string EcoRegion { get; set; }
        public string StationName { get; set; }
        public string StationStatus { get; set; }
        public Nullable<double> Elevation { get; set; }
        public string WaterShedRegion { get; set; }
        public Nullable<double> Longtitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string NearCity { get; set; }
        public string Move { get; set; }
        public string Description { get; set; }
        public Nullable<double> UTMX { get; set; }
        public Nullable<double> UTMY { get; set; }
        public string Region { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> USGS { get; set; }
        public Nullable<bool> StateEngineering { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public string StoretUploaded { get; set; }
    }
}
