//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartInfo
    {
        public int ptNODE { get; set; }
        public Nullable<int> ptPARENTNODE { get; set; }
        public string ptTEXT { get; set; }
        public string ptDOCURL { get; set; }
        public Nullable<bool> Valid { get; set; }
        public int ID { get; set; }
    }
}
