//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistration
    {
        public int ParticipantID { get; set; }
        public int RegistrationID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string WorkShop { get; set; }
        public bool Paid { get; set; }
        public bool Receipt { get; set; }
        public Nullable<bool> Attend { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
    }
}
