//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWBKey
    {
        public string WBID { get; set; }
        public string WATERSHED { get; set; }
        public string BASIN { get; set; }
        public string SUBBASIN { get; set; }
        public string REGION { get; set; }
        public string SEGMENT { get; set; }
        public string DESIG { get; set; }
        public string SegDesc { get; set; }
        public Nullable<System.DateTime> VerifyDate { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Valid { get; set; }
        public int ID { get; set; }
    }
}
