//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWatercode
    {
        public string WATERCODE { get; set; }
        public string WATERNAME { get; set; }
        public Nullable<bool> STREAM { get; set; }
        public Nullable<decimal> ACRESMILES { get; set; }
        public string LOCATION { get; set; }
        public string DRAINAGE { get; set; }
        public string DRAINNAME { get; set; }
        public string HYDROCODE { get; set; }
        public string COUNTY { get; set; }
        public string REGION { get; set; }
        public string AWMAREA { get; set; }
        public string STKCODE { get; set; }
        public string BIOLOGIST { get; set; }
        public string AREABIO { get; set; }
        public string ADDLDATA { get; set; }
        public string MAPCOORDIN { get; set; }
        public string ATLASPAGE { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<decimal> ELEVATION { get; set; }
        public Nullable<decimal> UT_ELEVATI { get; set; }
        public string OWNERSHIP { get; set; }
        public Nullable<bool> WILDERNESS { get; set; }
        public string BLMMAP { get; set; }
        public string TOPOMAP { get; set; }
        public Nullable<bool> OBSOLETE { get; set; }
        public Nullable<bool> Valid { get; set; }
        public int ID { get; set; }
    }
}
