//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblXSRep
    {
        public int XSID { get; set; }
        public int RepNum { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<bool> Valid { get; set; }
        public int ID { get; set; }
    }
}
