//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblX
    {
        public int XSID { get; set; }
        public Nullable<int> SampleID { get; set; }
        public Nullable<int> DistanceFromWQS { get; set; }
        public string DistUnit { get; set; }
        public string EnterDate { get; set; }
        public string Comments { get; set; }
    }
}
