//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlkPhysHabPara
    {
        public string LongParameterName { get; set; }
        public string ParameterName { get; set; }
        public string ParameterTypeI { get; set; }
        public string ParameterTypeII { get; set; }
        public string RowID { get; set; }
        public string CharGroupID { get; set; }
        public string Comments { get; set; }
        public string Description { get; set; }
        public Nullable<int> dsOrder { get; set; }
        public Nullable<bool> Valid { get; set; }
        public int ID { get; set; }
    }
}
