//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class trsChemParaMapColumn
    {
        public string TableName { get; set; }
        public string ColName { get; set; }
        public string RowID { get; set; }
        public string ChemParameter { get; set; }
        public Nullable<bool> Valid { get; set; }
        public int ID { get; set; }
    }
}
