//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRiverWatchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnknownSample
    {
        public int OrganizationID { get; set; }
        public int UnknownSampleID { get; set; }
        public string SampleType { get; set; }
        public string SampleNumber { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public Nullable<decimal> MeanValue { get; set; }
        public Nullable<decimal> TrueValue { get; set; }
        public Nullable<int> Round { get; set; }
        public string Comment { get; set; }
        public string OldValidated { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string UserLastModified { get; set; }
        public string BatchSampleNumber { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<bool> Validated { get; set; }
        public Nullable<decimal> PctRecovery { get; set; }
    }
}
